version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: student-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: studentDatabase
      MYSQL_USER: vishal_admin
      MYSQL_PASSWORD: StrongPass!123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app_net

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    image: vishalbhj/student-rest-api:${VERSION:-1.0.0}
    container_name: api1
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentDatabase?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: vishal_admin
      SPRING_DATASOURCE_PASSWORD: StrongPass!123

      DB_URL: jdbc:mysql://db:3306/studentDatabase?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Kolkata
      DB_USERNAME: vishal_admin
      DB_PASSWORD: StrongPass!123
    ports:
      - "8081:8087"
    networks:
      - app_net

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    image: vishalbhj/student-rest-api:${VERSION:-1.0.0}
    container_name: api2
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentDatabase?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: vishal_admin
      SPRING_DATASOURCE_PASSWORD: StrongPass!123

      DB_URL: jdbc:mysql://db:3306/studentDatabase?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Kolkata
      DB_USERNAME: vishal_admin
      DB_PASSWORD: StrongPass!123
    ports:
      - "8082:8087"
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    depends_on:
      - api1
      - api2
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
